[features]
seeds = false
skip-lint = false
[programs.localnet]
paper_clip_maximizer = "2m9g7TYbAcZwcT3TSxHh4czMS6s7jdNqGpPeNi378XeL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/galactus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
